### ISSUE TITLE
creating bamboo sessions. problem with user role

### ISSUE THREAD

**Issue by tomassabol** [MaartenVercammen/UCN-Semester-3-project#86]
Host, which is object of user retrieves role "ADMIN", but object recipe, which also contains object of user, retrieves role as int

<img width="178" alt="Screen Shot 2022-12-05 at 1 30 52 PM" src="https://user-images.githubusercontent.com/28631050/205637860-b417a527-1a25-40cf-9211-4770b6923e46.png">

**Comment by MaartenVercammen** [comment]
No Capitals begin letter please
